
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tain.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Fri Sep 21 17:20:28 KST 2018
 * Generated source version: 2.2.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsTestServiceImplService",
                      portName = "WsTestServiceImplPort",
                      targetNamespace = "http://ws.tain.org/",
                      wsdlLocation = "http://localhost:8080/CxfProvider01/services/WsTestServiceImplPort?wsdl",
                      endpointInterface = "org.tain.ws.WsTestServiceImpl")
                      
public class WsTestServiceImplImpl implements WsTestServiceImpl {

    private static final Logger LOG = Logger.getLogger(WsTestServiceImplImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tain.ws.WsTestServiceImpl#getMessage(java.lang.String  arg0 )*
     */
    public java.lang.String getMessage(java.lang.String arg0) { 
        LOG.info("Executing operation getMessage");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1330951688";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tain.ws.WsTestServiceImpl#main(java.util.List<java.lang.String>  arg0 )*
     */
    public void main(java.util.List<java.lang.String> arg0) { 
        LOG.info("Executing operation main");
        System.out.println(arg0);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
