
/*
 * 
 */

package org.tain.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.7
 * Fri Sep 21 17:20:28 KST 2018
 * Generated source version: 2.2.7
 * 
 */


@WebServiceClient(name = "WsTestServiceImplService", 
                  wsdlLocation = "http://localhost:8080/CxfProvider01/services/WsTestServiceImplPort?wsdl",
                  targetNamespace = "http://ws.tain.org/") 
public class WsTestServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.tain.org/", "WsTestServiceImplService");
    public final static QName WsTestServiceImplPort = new QName("http://ws.tain.org/", "WsTestServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CxfProvider01/services/WsTestServiceImplPort?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/CxfProvider01/services/WsTestServiceImplPort?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public WsTestServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsTestServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsTestServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns WsTestServiceImpl
     */
    @WebEndpoint(name = "WsTestServiceImplPort")
    public WsTestServiceImpl getWsTestServiceImplPort() {
        return super.getPort(WsTestServiceImplPort, WsTestServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsTestServiceImpl
     */
    @WebEndpoint(name = "WsTestServiceImplPort")
    public WsTestServiceImpl getWsTestServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsTestServiceImplPort, WsTestServiceImpl.class, features);
    }

}
