
package org.tain.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.7
 * Fri Sep 21 17:15:40 KST 2018
 * Generated source version: 2.2.7
 */

@XmlRootElement(name = "getMessageResponse", namespace = "http://ws.tain.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMessageResponse", namespace = "http://ws.tain.org/")

public class GetMessageResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

