
package org.tain.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.7
 * Fri Sep 21 17:15:40 KST 2018
 * Generated source version: 2.2.7
 */

@XmlRootElement(name = "mainResponse", namespace = "http://ws.tain.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mainResponse", namespace = "http://ws.tain.org/")

public class MainResponse {


}

