
package org.tain.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.7
 * Fri Sep 21 17:15:40 KST 2018
 * Generated source version: 2.2.7
 */

@XmlRootElement(name = "main", namespace = "http://ws.tain.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "main", namespace = "http://ws.tain.org/")

public class Main {

    @XmlElement(name = "arg0")
    private String[] arg0;

    public String[] getArg0() {
        return this.arg0;
    }

    public void setArg0(String[] newArg0)  {
        this.arg0 = newArg0;
    }

}

